version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./_fixtures/Dockerfile
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    environment:
      DB_HOST: db
      DB_USER: app
      DB_PASS: app
      DB_NAME: app
      JWT_ACCESS_SECRET: CHANGEME
      JWT_ACCESS_TTL: 15m
      JWT_REFRESH_SECRET: CHANGEME
      JWT_REFRESH_TTL: 1d
    ports:
      - 3000:3000
    depends_on:
      - db
      - phpmyadmin

  db:
    image: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_DATABASE: app
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: app
      PMA_PASSWORD: app
    ports:
      - 8080:80

volumes:
  mysql_data:
  node_modules:
